name: ▶️ Promote release candidate to production AppStore

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false # we don't want to abort releases

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy-production-long.yml
    secrets: inherit
